// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repos

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	DeleteContact(ctx context.Context, id uuid.UUID) error
	GetContactByID(ctx context.Context, id uuid.UUID) (Contact, error)
	GetContacts(ctx context.Context) ([]Contact, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
}

var _ Querier = (*Queries)(nil)
